# Large-Scale Stochastic Variational GP Regression (CUDA)

## Overview

In this notebook, we'll give an overview of how to use SVGP stochastic variational regression ((https://arxiv.org/pdf/1411.2005.pdf)) to rapidly train using minibatches on the `3droad` UCI dataset with hundreds of thousands of training examples. 

In [1]:
%set_env CUDA_VISIBLE_DEVICES=1

import math
import torch
import tqdm
import pyro
import gpytorch
from matplotlib import pyplot as plt

# Make plots inline
%matplotlib inline

pyro.clear_param_store()

env: CUDA_VISIBLE_DEVICES=1


## Loading Data

For this example notebook, we'll be using the `song` UCI dataset used in the paper. Running the next cell downloads a copy of the dataset that has already been scaled and normalized appropriately. For this notebook, we'll simply be splitting the data using the first 80% of the data as training and the last 20% as testing.

**Note**: Running the next cell will attempt to download a **~136 MB** file to the current directory.

In [2]:
import urllib.request
import os.path
from scipy.io import loadmat
from math import floor
    
data = torch.Tensor(loadmat('/home/jake.gardner/data/pol.mat')['data'])
X = data[:, :-1]
X = X - X.min(0)[0]
X = 2 * (X / X.max(0)[0]) - 1
y = data[:, -1]

# Use the first 80% of the data for training, and the last 20% for testing.
train_n = int(floor(0.8*len(X)))

train_x = X[:train_n, :].contiguous().cuda()
train_y = y[:train_n].contiguous().cuda()

test_x = X[train_n:, :].contiguous().cuda()
test_y = y[train_n:].contiguous().cuda()

In [3]:
print(train_x.size())

torch.Size([12000, 26])


## Creating a DataLoader

The next step is to create a torch `DataLoader` that will handle getting us random minibatches of data. This involves using the standard `TensorDataset` and `DataLoader` modules provided by PyTorch.

In this notebook we'll be using a fairly large batch size of 1024 just to make optimization run faster, but you could of course change this as you so choose.

In [4]:
from torch.utils.data import TensorDataset, DataLoader
train_dataset = TensorDataset(train_x, train_y)
train_loader = DataLoader(train_dataset, batch_size=1024, shuffle=True)

test_dataset = TensorDataset(test_x, test_y)
test_loader = DataLoader(test_dataset, batch_size=1024, shuffle=False)

## Defining the SVGP Model

We now define the GP regression module that, intuitvely, will act as the final "layer" of our neural network. In this case, because we are doing variational inference and *not* exact inference, we will be using an `AbstractVariationalGP`. In this example, because we will be learning the inducing point locations, we'll be using a base `VariationalStrategy` with `learn_inducing_locations=True`.

Because the feature extractor we defined above extracts two features, we'll need to define our grid bounds over two dimensions.

In [5]:
from gpytorch.models import SteinVariationalGP, SteinVariationalDeepGPLayer, SteinVariationalDeepGP


class GPLayer(SteinVariationalDeepGPLayer):
    def __init__(self, input_dims, output_dims, inducing_points, likelihood, num_data, name_prefix=""):
        super().__init__(
            input_dims,
            output_dims,
            inducing_points,
            likelihood=likelihood,
            num_data=num_data,
            name_prefix=name_prefix
        )
        self.mean_module = gpytorch.means.ConstantMean()
        if output_dims is not None:
            self.covar_module = gpytorch.kernels.ScaleKernel(
                gpytorch.kernels.MaternKernel(batch_shape=torch.Size([output_dims])),
                batch_shape=torch.Size([output_dims])
            )
        else:
            self.covar_module = gpytorch.kernels.ScaleKernel(
                gpytorch.kernels.MaternKernel()
            )
        
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

class DeepGP(SteinVariationalDeepGP):
    def __init__(self, train_x, name_prefix=""):
        likelihood = gpytorch.likelihoods.GaussianLikelihood()
        super().__init__(train_x.size(-2), likelihood, name_prefix)
        
        self.layer1 = GPLayer(
            input_dims=train_x.size(-1),
            output_dims=5,
            inducing_points=torch.randn(5, 256, train_x.size(-1)),
            likelihood=None,
            num_data=self.num_data,
            name_prefix=self.name_prefix + ".layer1",
        )
        
        self.layer2 = GPLayer(
            input_dims=self.layer1.output_dims,
            output_dims=None,
            inducing_points=torch.randn(256, self.layer1.output_dims),
            likelihood=None,
            num_data=self.num_data,
            name_prefix=self.name_prefix + ".layer2",
        )
        
    def forward(self, inputs):
        return self.layer2(self.layer1(inputs))

model = DeepGP(train_x, name_prefix="deep_gp").cuda()

In [6]:
x_batch, y_batch = next(iter(train_loader))

In [7]:
out = model(x_batch)
out.rsample().sum().backward()

## Training the Model

The cell below trains the model above, learning both the hyperparameters of the Gaussian process **and** the parameters of the neural network in an end-to-end fashion using Type-II MLE.

Unlike when using the exact GP marginal log likelihood, performing variational inference allows us to make use of stochastic optimization techniques. For this example, we'll do one epoch of training. Given the small size of the neural network relative to the size of the dataset, this should be sufficient to achieve comparable accuracy to what was observed in the DKL paper.

The optimization loop differs from the one seen in our more simple tutorials in that it involves looping over both a number of training iterations (epochs) *and* minibatches of the data. However, the basic process is the same: for each minibatch, we forward through the model, compute the loss (the `VariationalMarginalLogLikelihood` or ELBO), call backwards, and do a step of optimization.

In [15]:
pyro.clear_param_store()

from pyro import optim
from pyro import infer

optimizer = optim.Adam({"lr": 0.01})
num_epochs = 100

kernel = infer.RBFSteinKernel()
svi = infer.SVGD(model.model, kernel, optimizer, num_particles=16, max_plate_nesting=1)

for i in range(num_epochs):
    # Within each iteration, we will go over each minibatch of data
    loader = tqdm.tqdm_notebook(train_loader, desc=f"Train (Epoch {i + 1})")
    for x_batch, y_batch in loader:
        loss = svi.step(x_batch, y_batch)
        loader.set_postfix(
            os1=model.layer1.covar_module.outputscale.mean().item(),
            os2=model.layer2.covar_module.outputscale.mean().item(),
        )


ValueError: Shape mismatch inside plate('num_particles_vectorized') at site deep_gp.layer1.inducing_values dim -1, 16 vs 5
                                                     Trace Shapes:         
                                                      Param Sites:         
               deep_gp.gp_prior$$$likelihood.noise_covar.raw_noise        1
                         deep_gp.gp_prior$$$layer1.inducing_points 5 256 26
                    deep_gp.gp_prior$$$layer1.mean_module.constant        1
            deep_gp.gp_prior$$$layer1.covar_module.raw_outputscale        5
deep_gp.gp_prior$$$layer1.covar_module.base_kernel.raw_lengthscale 5   1  1
                         deep_gp.gp_prior$$$layer2.inducing_points   256  5
                    deep_gp.gp_prior$$$layer2.mean_module.constant        1
            deep_gp.gp_prior$$$layer2.covar_module.raw_outputscale         
deep_gp.gp_prior$$$layer2.covar_module.base_kernel.raw_lengthscale     1  1
                                                     Sample Sites:         
                                     num_particles_vectorized dist        |
                                                             value    16  |
Trace Shapes:
 Param Sites:
Sample Sites:

In [10]:
loss

{'deep_gp.layer1.inducing_values': 57177.6875,
 'deep_gp.layer2.inducing_values': 31904.1875}

In [11]:
train_x.size()

torch.Size([12000, 26])

## Making Predictions

The next cell gets the predictive covariance for the test set (and also technically gets the predictive mean, stored in `preds.mean()`). Because the test set is substantially smaller than the training set, we don't need to make predictions in mini batches here, although this can be done by passing in minibatches of `test_x` rather than the full tensor.

In [12]:
model.eval()
# likelihood.eval()
all_means = []
all_vars = []
all_log_probs = []
with torch.no_grad(), pyro.condition(data=svi.get_named_particles()):
    for x_batch, y_batch in test_loader:
        preds = model.likelihood(model(x_batch))
        means = preds.mean.mean(dim=0).mean(dim=0).cpu()
        vars = preds.variance.mean(dim=0).mean(dim=0).cpu()
        log_probs = torch.distributions.Normal(
            means, vars.clamp_min(1e-5).sqrt()
        ).log_prob(y_batch.cpu())

        all_means.append(means)
        all_vars.append(vars)
        all_log_probs.append(log_probs)

means = torch.cat(all_means)
vars = torch.cat(all_vars)
log_probs = torch.cat(all_log_probs)

In [13]:
print('Test MAE: {}'.format(torch.mean(torch.abs(means - test_y.cpu()))))

Test MAE: 4.6444292068481445


In [14]:
print('Test NLL: {}'.format(-torch.mean(log_probs)))

Test NLL: 7.160470008850098


In [20]:
print(vars.min(), vars.mean(), vars.max())

tensor(3.5147) tensor(4.7498) tensor(6.5966)


In [22]:
model.likelihood.noise

tensor([3.3759], device='cuda:0', grad_fn=<AddBackward0>)

In [23]:
means

tensor([-28.2231,  70.3779,  67.9527,  ...,  58.4248, -28.9289, -18.7264])

In [24]:
test_y

tensor([-28.9453,  71.0547,  71.0547,  ...,  71.0547, -28.9453, -28.9453],
       device='cuda:0')